In [3]:
"""Створіть одновимірний масив (вектор) зі значеннями n!, факторіала кожного натурального числа n, починаючи з 1, та виведіть його значення. """
def factorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * factorial(n - 1)

n = 10  # Задайте бажану кількість елементів у векторі

factorial_vector = [factorial(i) for i in range(1, n + 1)]

# Виведення значень вектора факторіалів
print("Значення вектора факторіалів для перших", n, "натуральних чисел:")
print(factorial_vector)

Значення вектора факторіалів для перших 10 натуральних чисел:
[1, 2, 6, 24, 120, 720, 5040, 40320, 362880, 3628800]


In [1]:
"""Створіть двовимірний масив (матрицю) розміром 3x3, 
заповніть його оберненими значеннями косинусів кожного натурального числа, починаючи з 1, та виведіть його значення. """

import numpy as np

# Функція для обчислення оберненого значення косинусу
def inverse_cosine(n):
    return 1 / np.cos(n)

# Створення двовимірного масиву розміром 3x3
matrix = np.empty((3, 3))

# Заповнення матриці оберненими значеннями косинусів
for i in range(3):
    for j in range(3):
        matrix[i, j] = inverse_cosine((i * 3) + j + 1)  # Обчислення оберненого косинусу для кожного елементу

# Виведення значень матриці
print("Значення матриці з оберненими значеннями косинусів:")
print(matrix)

Значення матриці з оберненими значеннями косинусів:
[[ 1.85081572 -2.40299796 -1.01010867]
 [-1.52988566  3.52532009  1.04148193]
 [ 1.3264319  -6.87285064 -1.09753791]]


In [2]:
"""Створіть масив розміром 8x8, заповніть його випадковими дійсними числами 
від -1 до 1 та знайдіть відсоток чисел, які менше нуля та мають непарний індекс. """
import numpy as np

# Задання розміру матриці
size = (8, 8)

# Генерація масиву розміром 8x8 з випадковими дійсними числами від -1 до 1
random_matrix = np.random.uniform(-1, 1, size)

# Знаходження елементів, які менше нуля та мають непарний індекс
negative_odd_indices_count = np.sum((random_matrix < 0) & ((np.indices(size)[0] % 2 != 0) & (np.indices(size)[1] % 2 != 0)))

# Знаходження відсотку таких елементів відносно загальної кількості елементів
total_elements = size[0] * size[1]
percentage = (negative_odd_indices_count / total_elements) * 100

print(f"Відсоток чисел, менших за нуль та з непарним індексом: {percentage:.2f}%")

Відсоток чисел, менших за нуль та з непарним індексом: 15.62%


In [3]:
"""Створіть масив розміром 8x8, заповніть його випадковими дійсними числами 
від -1 до 1 та знайдіть відсоток чисел, які менше нуля та мають непарний індекс. """

import numpy as np

# Генерація масиву розміром 8x8 з випадковими дійсними числами від -1 до 1
random_matrix = np.random.uniform(-1, 1, (8, 8))

# Знаходження елементів, які менше нуля та мають непарні індекси
negative_odd_indices_count = np.sum((random_matrix < 0) & (np.indices((8, 8)).sum(axis=0) % 2 != 0))

# Знаходження відсотку таких елементів відносно загальної кількості елементів
total_elements = random_matrix.size
percentage = (negative_odd_indices_count / total_elements) * 100

print(f"Відсоток чисел, менших за нуль та з непарним індексом: {percentage:.2f}%")

Відсоток чисел, менших за нуль та з непарним індексом: 25.00%


In [4]:
"""Створіть два одновимірних масиви розміром 5, 
заповніть їх випадковими цілими числами в діапазоні від 2 до 7 та виконайте на них поелементні операції додавання, віднімання та множення. """
import numpy as np

# Задання розміру масивів
size = 5

# Генерація двох масивів розміром 5 з випадковими цілими числами в діапазоні від 2 до 7
array1 = np.random.randint(2, 8, size)
array2 = np.random.randint(2, 8, size)

print("Перший масив:", array1)
print("Другий масив:", array2)

# Виконання поелементних операцій: додавання, віднімання та множення
addition_result = np.add(array1, array2)
subtraction_result = np.subtract(array1, array2)
multiplication_result = np.multiply(array1, array2)

print("\nРезультат додавання:", addition_result)
print("Результат віднімання:", subtraction_result)
print("Результат множення:", multiplication_result)

Перший масив: [5 7 4 6 2]
Другий масив: [4 3 3 6 3]

Результат додавання: [ 9 10  7 12  5]
Результат віднімання: [ 1  4  1  0 -1]
Результат множення: [20 21 12 36  6]


In [5]:
"""Створіть два вектори розміром 7, заповніть їх довільними цілими числами та знайдіть їх скалярний добуток. """
import numpy as np

# Створення двох векторів розміром 7 з довільними цілими числами
vector1 = np.random.randint(1, 10, 7)
vector2 = np.random.randint(1, 10, 7)

print("Перший вектор:", vector1)
print("Другий вектор:", vector2)

# Обчислення скалярного добутку двох векторів
dot_product = np.dot(vector1, vector2)

print("\nСкалярний добуток двох векторів:", dot_product)

Перший вектор: [1 9 1 7 3 1 6]
Другий вектор: [7 2 4 7 6 2 3]

Скалярний добуток двох векторів: 116


In [6]:
"""Створіть дві матриці розміром 2x3 та 3x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 15 та перемножте їх між собою. """
import numpy as np

# Створення двох матриць розміром 2x3 та 3x4 з випадковими цілими числами
matrix1 = np.random.randint(1, 16, (2, 3))
matrix2 = np.random.randint(1, 16, (3, 4))

print("Перша матриця:")
print(matrix1)
print("\nДруга матриця:")
print(matrix2)

# Перемноження двох матриць
result_matrix = np.dot(matrix1, matrix2)

print("\nРезультат множення двох матриць:")
print(result_matrix)

Перша матриця:
[[6 6 6]
 [9 3 7]]

Друга матриця:
[[ 9  9 10  8]
 [ 6  3  1  4]
 [15  8  1  3]]

Результат множення двох матриць:
[[180 120  72  90]
 [204 146 100 105]]


In [7]:
"""Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 15 та знайдіть її обернену матрицю. """
import numpy as np

# Створення матриці розміром 3x3 з випадковими цілими числами
matrix = np.random.randint(1, 16, (3, 3))

print("Початкова матриця:")
print(matrix)

# Перевірка, чи можна знайти обернену матрицю
if np.linalg.det(matrix) != 0:  # Перевірка на невиродженість матриці
    inverse_matrix = np.linalg.inv(matrix)
    print("\nОбернена матриця:")
    print(inverse_matrix)
else:
    print("\nОбернена матриця не існує, оскільки вихідна матриця є виродженою.")

Початкова матриця:
[[ 1 10  9]
 [10 12  4]
 [ 8  8  5]]

Обернена матриця:
[[-0.09459459 -0.07432432  0.22972973]
 [ 0.06081081  0.22635135 -0.29054054]
 [ 0.05405405 -0.24324324  0.2972973 ]]


In [8]:
"""Створіть матрицю розміром 7x7, заповніть її випадковими дійсними числами в діапазоні від 0 до 10 та транспонуйте її. """
import numpy as np

# Створення матриці розміром 7x7 з випадковими дійсними числами від 0 до 10
matrix = np.random.uniform(0, 10, (7, 7))

print("Початкова матриця:")
print(matrix)

# Транспонування матриці
transposed_matrix = np.transpose(matrix)

print("\nТранспонована матриця:")
print(transposed_matrix)

Початкова матриця:
[[8.73888235 6.96863746 1.98912671 2.41775454 4.62329458 1.00952408
  1.81727566]
 [2.71386869 9.47911939 0.34640013 3.64764217 2.48546551 0.49895328
  8.85394656]
 [5.24872025 8.29447247 1.21075992 9.99835514 2.47786887 8.91236351
  9.20111521]
 [6.22512234 3.8739099  5.59725422 3.69126858 0.77465111 9.74297902
  6.63726199]
 [8.59150154 3.88435875 3.62917148 1.70836837 4.57767382 2.86220765
  6.86769935]
 [3.95630128 8.91543378 4.57007188 4.27411695 1.00577613 1.44510442
  8.49630265]
 [4.05681302 6.41096521 5.55636319 1.56436132 1.570405   7.76541576
  4.38867011]]

Транспонована матриця:
[[8.73888235 2.71386869 5.24872025 6.22512234 8.59150154 3.95630128
  4.05681302]
 [6.96863746 9.47911939 8.29447247 3.8739099  3.88435875 8.91543378
  6.41096521]
 [1.98912671 0.34640013 1.21075992 5.59725422 3.62917148 4.57007188
  5.55636319]
 [2.41775454 3.64764217 9.99835514 3.69126858 1.70836837 4.27411695
  1.56436132]
 [4.62329458 2.48546551 2.47786887 0.77465111 4.577673

In [9]:
"""Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть матрицю випадковими дійсними числами від 0 до 1,
а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор. """

import numpy as np

# Створення матриці розміром 3x4 з випадковими дійсними числами від 0 до 1
matrix = np.random.rand(3, 4)

print("Матриця:")
print(matrix)

# Створення вектора розміром 4 з випадковими цілими числами від 1 до 10
vector = np.random.randint(1, 11, 4)

print("\nВектор:")
print(vector)

# Знаходження добутку матриці на вектор
result = np.dot(matrix, vector)

print("\nДобуток матриці на вектор:")
print(result)

Матриця:
[[0.58654544 0.54476726 0.43011212 0.95202648]
 [0.21748055 0.33179495 0.42985023 0.02145576]
 [0.71259347 0.43401634 0.62520273 0.70157701]]

Вектор:
[10  5  5  7]

Добуток матриці на вектор:
[17.40403667  6.13322168 17.33306906]


In [10]:
"""Створіть матрицю розміром 2x3 та вектор розміром 3, 
заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами від 0 до 1, 
і знайдіть суму добутків елементів кожного рядка матриці на відповідний елемент вектору. """

import numpy as np

# Створення матриці розміром 2x3 з випадковими дійсними числами від 0 до 1
matrix = np.random.rand(2, 3)

print("Матриця:")
print(matrix)

# Створення вектора розміром 3 з випадковими дійсними числами від 0 до 1
vector = np.random.rand(3)

print("\nВектор:")
print(vector)

# Знаходження суми добутків елементів кожного рядка матриці на відповідний елемент вектору
result = np.sum(matrix * vector, axis=1)

print("\nСума добутків елементів кожного рядка матриці на відповідний елемент вектору:")
print(result)

Матриця:
[[0.87100379 0.03367683 0.4732718 ]
 [0.71856261 0.78159099 0.26113581]]

Вектор:
[0.27682629 0.50012332 0.41028863]

Сума добутків елементів кожного рядка матриці на відповідний елемент вектору:
[0.45213736 0.69694996]


In [11]:
"""Створіть дві матриці розміром 5x5, 
заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть різницю всіх елементів другої матриці. """
import numpy as np

# Створення двох матриць розміром 5x5 з випадковими цілими числами від 1 до 10
matrix1 = np.random.randint(1, 11, (5, 5))
matrix2 = np.random.randint(1, 11, (5, 5))

print("Перша матриця:")
print(matrix1)
print("\nДруга матриця:")
print(matrix2)

# Обчислення різниці всіх елементів другої матриці
difference = np.sum(matrix2) - np.sum(matrix1)

print("\nРізниця всіх елементів другої матриці:", difference)


Перша матриця:
[[ 1 10  2  3  6]
 [ 3  3  8  2  3]
 [10  6  3  8  2]
 [ 2  6  7  7  6]
 [ 2  7  2  4  6]]

Друга матриця:
[[ 8  3  7  6  6]
 [ 9  9  1  6  6]
 [ 9  6  2 10 10]
 [10  4  9  5  5]
 [ 4  2  9  9 10]]

Різниця всіх елементів другої матриці: 46


In [12]:
"""Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть добуток їх елементів. """
import numpy as np

# Створення двох матриць розміром 3x3 з випадковими цілими числами від 1 до 10
matrix1 = np.random.randint(1, 11, (3, 3))
matrix2 = np.random.randint(1, 11, (3, 3))

print("Перша матриця:")
print(matrix1)
print("\nДруга матриця:")
print(matrix2)

# Обчислення добутку елементів матриці
product = np.prod(matrix1) * np.prod(matrix2)

print("\nДобуток елементів двох матриць:", product)

Перша матриця:
[[ 9  6  4]
 [ 2  9 10]
 [ 6  6  8]]

Друга матриця:
[[ 4  4  9]
 [ 9  9  6]
 [ 1 10  4]]

Добуток елементів двох матриць: 994312192


C:\Users\nik02\AppData\Local\Temp\ipykernel_11844\2263062932.py:14: RuntimeWarning: overflow encountered in scalar multiply
  product = np.prod(matrix1) * np.prod(matrix2)


In [13]:
"""Створіть матрицю розміром 8x8, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів на побічній діагоналі. """
import numpy as np

# Створення матриці розміром 8x8 з випадковими цілими числами від 1 до 100
matrix = np.random.randint(1, 101, (8, 8))

print("Матриця:")
print(matrix)

# Знаходження суми елементів на побічній діагоналі
diagonal_sum = np.trace(np.fliplr(matrix))

print("\nСума елементів на побічній діагоналі:", diagonal_sum)

Матриця:
[[ 70  25  27  52  59  89  14  79]
 [ 36  59  94  49  10  63 100  74]
 [  6  78  87  27  79  75  70   8]
 [  2  15  13  66  36  48  83  58]
 [  4  90  97  50  72  41  39  92]
 [ 35  30  74  70   1   1  84  97]
 [ 50  85  77  54  35  67  76  11]
 [ 55  13  42  55  81  52  93  78]]

Сума елементів на побічній діагоналі: 554


In [14]:
"""Створіть матрицю розміром 5x5, заповніть її випадковими дійсними числами в діапазоні від -2 до 2 та знайдіть вектор-стовпчик, 
що містить найменше за модулем значення елементу у кожному стовпці матриці. """

import numpy as np

# Створення матриці розміром 5x5 з випадковими дійсними числами від -2 до 2
matrix = np.random.uniform(-2, 2, (5, 5))

print("Матриця:")
print(matrix)

# Знаходження вектора-стовпчика з найменшим за модулем значенням у кожному стовпці
min_abs_column_values = np.min(np.abs(matrix), axis=0)
min_abs_indices = np.argmin(np.abs(matrix), axis=0)

result_vector = np.array([matrix[min_abs_indices[i], i] for i in range(len(min_abs_indices))])

print("\nВектор-стовпчик з найменшими за модулем значеннями:")
print(result_vector)

Матриця:
[[-0.326921    1.09269795 -0.51547107 -1.32642875  0.7374658 ]
 [-0.55067638 -1.97777664 -1.05869976  0.01708759 -1.34047265]
 [-0.55129855 -0.18120689 -0.37367501 -1.36967361  0.48916841]
 [ 0.02173525 -0.40768678 -0.34268332 -1.15007774  1.9009867 ]
 [ 1.66951284  0.32787356 -1.15526441 -0.16063279 -1.75698238]]

Вектор-стовпчик з найменшими за модулем значеннями:
[ 0.02173525 -0.18120689 -0.34268332  0.01708759  0.48916841]
